package com.lei.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rjwl.reginet.xinread.model.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "STUDENT";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StudentId = new Property(0, long.class, "studentId", true, "_id");
        public final static Property Id = new Property(1, int.class, "id", false, "ID");
        public final static Property Username = new Property(2, String.class, "username", false, "USERNAME");
        public final static Property Password = new Property(3, String.class, "password", false, "PASSWORD");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Gender = new Property(5, String.class, "gender", false, "GENDER");
        public final static Property Schoolname = new Property(6, String.class, "schoolname", false, "SCHOOLNAME");
        public final static Property HeadPic = new Property(7, String.class, "headPic", false, "HEAD_PIC");
        public final static Property ClassID = new Property(8, int.class, "classID", false, "CLASS_ID");
        public final static Property GradeID = new Property(9, int.class, "gradeID", false, "GRADE_ID");
        public final static Property Yesorno = new Property(10, int.class, "yesorno", false, "YESORNO");
    }


    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: studentId
                "\"ID\" INTEGER NOT NULL ," + // 1: id
                "\"USERNAME\" TEXT," + // 2: username
                "\"PASSWORD\" TEXT," + // 3: password
                "\"NAME\" TEXT," + // 4: name
                "\"GENDER\" TEXT," + // 5: gender
                "\"SCHOOLNAME\" TEXT," + // 6: schoolname
                "\"HEAD_PIC\" TEXT," + // 7: headPic
                "\"CLASS_ID\" INTEGER NOT NULL ," + // 8: classID
                "\"GRADE_ID\" INTEGER NOT NULL ," + // 9: gradeID
                "\"YESORNO\" INTEGER NOT NULL );"); // 10: yesorno
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStudentId());
        stmt.bindLong(2, entity.getId());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(4, password);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
 
        String schoolname = entity.getSchoolname();
        if (schoolname != null) {
            stmt.bindString(7, schoolname);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(8, headPic);
        }
        stmt.bindLong(9, entity.getClassID());
        stmt.bindLong(10, entity.getGradeID());
        stmt.bindLong(11, entity.getYesorno());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getStudentId());
        stmt.bindLong(2, entity.getId());
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(3, username);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(4, password);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(6, gender);
        }
 
        String schoolname = entity.getSchoolname();
        if (schoolname != null) {
            stmt.bindString(7, schoolname);
        }
 
        String headPic = entity.getHeadPic();
        if (headPic != null) {
            stmt.bindString(8, headPic);
        }
        stmt.bindLong(9, entity.getClassID());
        stmt.bindLong(10, entity.getGradeID());
        stmt.bindLong(11, entity.getYesorno());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.getLong(offset + 0), // studentId
            cursor.getInt(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // username
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // password
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // gender
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // schoolname
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // headPic
            cursor.getInt(offset + 8), // classID
            cursor.getInt(offset + 9), // gradeID
            cursor.getInt(offset + 10) // yesorno
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setStudentId(cursor.getLong(offset + 0));
        entity.setId(cursor.getInt(offset + 1));
        entity.setUsername(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPassword(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setGender(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSchoolname(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setHeadPic(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setClassID(cursor.getInt(offset + 8));
        entity.setGradeID(cursor.getInt(offset + 9));
        entity.setYesorno(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setStudentId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getStudentId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Student entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
